services:
  - type: web
    name: sharedlm-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: MEM0_API_KEY
        sync: false
      - key: DEFAULT_MODEL_OPENAI
        sync: false
      - key: DEFAULT_MODEL_ANTHROPIC
        sync: false
      - key: DEFAULT_TOP_K
        sync: false